# Data Understanding

### Objective

Understand the source datasets before performing any transformation.
Inspect the structure, columns, data types and data quality.

In [1]:
import pandas as pd
from pathlib import Path

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

In [2]:
DATA_PATH = Path("../Data/Raw")
DATA_PATH

WindowsPath('../Data/Raw')

In [ ]:
# Load Dataset 
# Reading the three source CSV files into Pandas DataFrames.

customers = pd.read_csv(DATA_PATH / "customers.csv")
transactions = pd.read_csv(DATA_PATH / "transactions.csv")
amlnet = pd.read_csv(DATA_PATH / "AMLNet_v2_transactions.csv")

In [4]:
print(f"Customers Shape      : {customers.shape}")
print(f"Transactions Shape   : {transactions.shape}")
print(f"AMLNet Shape         : {amlnet.shape}")

Customers Shape      : (60000, 1)
Transactions Shape   : (1000000, 8)
AMLNet Shape         : (1090000, 17)

# Source Data Inventory

### Objective

Identify all source datasets, understand their purpose and determine how each dataset contributes to the Enterprise Banking Data Platform.
This establishes a clear understanding of the available data before designing the ETL process.


-> Check N0. of Rows & Columns 

.shape returns a tuple:
Number of rows & 
Number of columns.

-> Quick Inspect 

.head() displays the first 5 rows of the DataFrame. Useful for a quick inspection of the dataset.

-> Check Information

.info() displays: 
Total rows,
Column names,
Data types,
Non-null counts,
Memory usage.

-> Check Columns

.columns returns the names of all columns in the DataFrame.

In [6]:
customers.shape

(60000, 1)

In [ ]:
customers.head(10)

   customer_id
0        30001
1        30002
2        30003
3        30004
4        30005

In [9]:
customers.columns

Index(['customer_id'], dtype='str')

In [14]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 60000 entries, 0 to 59999
Data columns (total 1 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   customer_id  60000 non-null  int64
dtypes: int64(1)
memory usage: 468.9 KB

In [15]:
transactions.head(10)

,transaction_id,customer_id,transaction_timestamp,amount,merchant_category,is_fraud,year,month
0,500006,49108,2023-05-06T00:00:00.000+02:00,274.130334,travel,0,2023,5
1,500010,39120,2023-05-15T00:00:00.000+02:00,967.288681,groceries,0,2023,5
2,500018,50180,2023-05-24T00:00:00.000+02:00,645.607027,travel,0,2023,5
3,500019,3885,2023-05-09T00:00:00.000+02:00,33.224846,fashion,0,2023,5
4,500020,43392,2023-05-12T00:00:00.000+02:00,679.432261,electronics,0,2023,5
5,500026,302,2023-05-25T00:00:00.000+02:00,445.011426,electronics,0,2023,5
6,500096,37544,2023-05-03T00:00:00.000+02:00,412.037554,gaming,0,2023,5
7,500111,45285,2023-05-07T00:00:00.000+02:00,174.993923,gaming,0,2023,5
8,500112,28783,2023-05-01T00:00:00.000+02:00,784.655851,fashion,0,2023,5
9,500114,23205,2023-05-21T00:00:00.000+02:00,56.273355,groceries,0,2023,5

In [17]:
transactions.columns

Index(['transaction_id', 'customer_id', 'transaction_timestamp', 'amount',
       'merchant_category', 'is_fraud', 'year', 'month'],
      dtype='str')

In [20]:
transactions.shape

(1000000, 8)

In [19]:
transactions.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 8 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   transaction_id         1000000 non-null  int64
 1   customer_id            1000000 non-null  int64
 2   transaction_timestamp  1000000 non-null  str
 3   amount                 1000000 non-null  float64
 4   merchant_category      1000000 non-null  str
 5   is_fraud               1000000 non-null  int64
 6   year                   1000000 non-null  int64
 7   month                  1000000 non-null  int64
dtypes: float64(1), int64(5), str(2)
memory usage: 61.0 MB

In [21]:
amlnet.shape

(1090000, 17)

In [22]:
amlnet.columns

Index(['step', 'type', 'amount', 'category', 'nameOrig', 'nameDest',
       'oldbalanceOrg', 'newbalanceOrig', 'isFraud', 'isMoneyLaundering',
       'laundering_typology', 'metadata', 'fraud_probability', 'hour',
       'day_of_week', 'day_of_month', 'month'],
      dtype='str')

In [23]:
amlnet.head(10)

,step,type,amount,category,nameOrig,nameDest,oldbalanceOrg,newbalanceOrig,isFraud,isMoneyLaundering,laundering_typology,metadata,fraud_probability,hour,day_of_week,day_of_month,month
0,0,BPAY,121.231873,Food,C4638,C1811,332687.934283,332566.702410,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,17,0,13,10
1,0,OSKO,98.099062,Other,C5536,C6852,455880.908413,455782.809350,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,18,0,13,10
2,0,DEBIT,93.861773,Healthcare,C450,C4987,266729.197862,266635.336089,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,18,0,13,10
3,0,BPAY,156.833185,Other,C503,C99,497635.915154,497479.081970,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,18,0,13,10
4,0,DEBIT,63.286125,Transport,C4791,C7610,350189.092731,350125.806606,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,19,0,13,10
5,0,DEBIT,497.754560,Education,C3803,M456,477502.120512,477004.365952,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,20,0,13,10
6,0,BPAY,1861.738692,Housing,C5916,M543,337017.091867,335155.353176,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,20,0,13,10
7,0,DEBIT,158.307183,Other,C7577,C324,336301.356107,336143.048924,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,21,0,13,10
8,0,TRANSFER,170.424306,Recreation,C450,C4885,267047.707623,266877.283317,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,22,0,13,10
9,0,BPAY,61.152910,Transport,C7954,C5277,442212.663250,442151.510340,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,22,0,13,10

In [24]:
amlnet.info()

<class 'pandas.DataFrame'>
RangeIndex: 1090000 entries, 0 to 1089999
Data columns (total 17 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   step                 1090000 non-null  int64
 1   type                 1090000 non-null  str
 2   amount               1090000 non-null  float64
 3   category             1090000 non-null  str
 4   nameOrig             1090000 non-null  str
 5   nameDest             1090000 non-null  str
 6   oldbalanceOrg        1090000 non-null  float64
 7   newbalanceOrig       1090000 non-null  float64
 8   isFraud              1090000 non-null  int64
 9   isMoneyLaundering    1090000 non-null  int64
 10  laundering_typology  1090000 non-null  str
 11  metadata             1090000 non-null  str
 12  fraud_probability    1080000 non-null  float64
 13  hour                 1090000 non-null  int64
 14  day_of_week          1090000 non-null  int64
 15  day_of_month         1090000 non-null  int64
 16  month                1090000 non-null  int64
dtypes: float64(4), int64(7), str(6)
memory usage: 141.4 MB

In [ ]:
# Dataset Summary

dataset_summary = pd.DataFrame({
    "Dataset": [
        "customers.csv",
        "transactions.csv",
        "AMLNet_v2_transactions.csv"
    ],
    "Source": [
        "Synthetic Banking Dataset",
        "Synthetic Banking Dataset",
        "AMLNet Dataset"
    ],
    "Purpose": [
        "Master list of customers",
        "Banking transactions",
        "AML & Fraud detection transactions"
    ],
    "Rows": [
        customers.shape[0],
        transactions.shape[0],
        amlnet.shape[0]
    ],
    "Columns": [
        customers.shape[1],
        transactions.shape[1],
        amlnet.shape[1]
    ]
})

dataset_summary

,Dataset,Source,Purpose,Rows,Columns
0,customers.csv,Synthetic Banking Dataset,Master list of customers,60000,1
1,transactions.csv,Synthetic Banking Dataset,Banking transactions,1000000,8
2,AMLNet_v2_transactions.csv,AMLNet Dataset,AML & Fraud detection transactions,1090000,17

# Customer Dataset Profiling

### Objective

Analyze the customer dataset to verify its quality and structure.
Identify missing values, duplicate records and understand the available customer information.


-> Check Missing Values

.isnull() identifies missing values.
.sum() counts missing values in each column.

-> Check Duplicate Records

.duplicated() identifies duplicate rows.
.sum() counts the number of duplicate records.

-> Count Unique Customers

.nunique() counts distinct values in the column.

-> Descriptive Statistics

.describe() returns:
Count
Mean
Standard deviation
Minimum
Quartiles
Maximum

In [26]:
customers.isnull().sum()

customer_id    0
dtype: int64

In [27]:
customers.duplicated().sum()

np.int64(0)

In [28]:
customers["customer_id"].nunique()

60000

In [29]:
customers.describe()

        customer_id
count  60000.000000
mean   30000.500000
std    17320.652413
min        1.000000
25%    15000.750000
50%    30000.500000
75%    45000.250000
max    60000.000000

# Banking Transactions Dataset Profiling

### Objective

Analyze the banking transaction dataset to understand its structure, data quality and business information.
This dataset will serve as the primary transactional source for the Enterprise Banking Data Platform.

In [33]:
transactions.isnull().sum()

transaction_id           0
customer_id              0
transaction_timestamp    0
amount                   0
merchant_category        0
is_fraud                 0
year                     0
month                    0
dtype: int64

In [34]:
transactions.duplicated().sum()

np.int64(0)

In [35]:
transactions["transaction_id"].nunique()

1000000

In [36]:
transactions.describe()

,transaction_id,customer_id,amount,is_fraud,year,month
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.0,1000000.000000
mean,499999.500000,29991.703616,499.828999,0.029999,2023.0,6.527958
std,288675.278932,17326.374340,288.818050,0.170585,0.0,3.446809
min,0.000000,0.000000,0.000420,0.000000,2023.0,1.000000
25%,249999.750000,14960.000000,249.372740,0.000000,2023.0,4.000000
50%,499999.500000,29973.000000,499.888646,0.000000,2023.0,7.000000
75%,749999.250000,45008.000000,750.013501,0.000000,2023.0,10.000000
max,999999.000000,59999.000000,999.998865,1.000000,2023.0,12.000000

# AML Transaction Dataset Profiling

### Objective

Analyze the AML transaction dataset to understand its structure, data quality and anti-money laundering attributes.
This dataset will later be integrated with the banking transactions for fraud and AML analysis.

In [37]:
amlnet.isnull().sum()

step                       0
type                       0
amount                     0
category                   0
nameOrig                   0
nameDest                   0
oldbalanceOrg              0
newbalanceOrig             0
isFraud                    0
isMoneyLaundering          0
laundering_typology        0
metadata                   0
fraud_probability      10000
hour                       0
day_of_week                0
day_of_month               0
month                      0
dtype: int64

In [38]:
amlnet.duplicated().sum()

np.int64(0)

In [41]:
amlnet.head()

,step,type,amount,category,nameOrig,nameDest,oldbalanceOrg,newbalanceOrig,isFraud,isMoneyLaundering,laundering_typology,metadata,fraud_probability,hour,day_of_week,day_of_month,month
0,0,BPAY,121.231873,Food,C4638,C1811,332687.934283,332566.702410,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,17,0,13,10
1,0,OSKO,98.099062,Other,C5536,C6852,455880.908413,455782.809350,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,18,0,13,10
2,0,DEBIT,93.861773,Healthcare,C450,C4987,266729.197862,266635.336089,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,18,0,13,10
3,0,BPAY,156.833185,Other,C503,C99,497635.915154,497479.081970,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,18,0,13,10
4,0,DEBIT,63.286125,Transport,C4791,C7610,350189.092731,350125.806606,0,0,normal,"{'timestamp': datetime.datetime(2025, 10, 13, ...",NaN,19,0,13,10

# Data Understanding - Key Observations

### Objective

Summarize the important findings identified during source data exploration.
These observations will guide the ETL design and data warehouse modeling.

In [42]:
observations = [
    "customers.csv contains a master list of unique customer IDs.",
    "transactions.csv is the primary banking transaction dataset with no missing or duplicate records.",
    "AMLNet_v2_transactions.csv is an independent AML dataset used for fraud and money laundering analysis.",
    "Only the fraud_probability column contains missing values (10,000 records).",
    "transactions.csv customer IDs use a different range than customers.csv and require validation during ETL.",
    "The metadata column contains nested information stored as text and will be evaluated during transformation."
]

for i, observation in enumerate(observations, start=1):
    print(f"{i}. {observation}")

1. customers.csv contains a master list of unique customer IDs.
2. transactions.csv is the primary banking transaction dataset with no missing or duplicate records.
3. AMLNet_v2_transactions.csv is an independent AML dataset used for fraud and money laundering analysis.
4. Only the fraud_probability column contains missing values (10,000 records).
5. transactions.csv customer IDs use a different range than customers.csv and require validation during ETL.
6. The metadata column contains nested information stored as text and will be evaluated during transformation.